# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'card_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_config(object):
    def setupUi(self, config):
        config.setObjectName("config")
        config.resize(802, 636)
        self.centralwidget = QtWidgets.QWidget(config)
        self.centralwidget.setObjectName("centralwidget")
        self.done = QtWidgets.QPushButton(self.centralwidget)
        self.done.setGeometry(QtCore.QRect(60, 400, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.done.setFont(font)
        self.done.setObjectName("done")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 40, 151, 331))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.open_card = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.open_card.setFont(font)
        self.open_card.setObjectName("open_card")
        self.verticalLayout.addWidget(self.open_card)
        self.close_card = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.close_card.setFont(font)
        self.close_card.setObjectName("close_card")
        self.verticalLayout.addWidget(self.close_card)
        self.clock_frequency = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.clock_frequency.setFont(font)
        self.clock_frequency.setObjectName("clock_frequency")
        self.clock_frequency.addItem("")
        self.clock_frequency.addItem("")
        self.clock_frequency.addItem("")
        self.clock_frequency.addItem("")
        self.clock_frequency.addItem("")
        self.clock_frequency.addItem("")
        self.verticalLayout.addWidget(self.clock_frequency)
        self.output_mode = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.output_mode.setFont(font)
        self.output_mode.setObjectName("output_mode")
        self.output_mode.addItem("")
        self.output_mode.addItem("")
        self.output_mode.addItem("")
        self.output_mode.addItem("")
        self.verticalLayout.addWidget(self.output_mode)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(250, 80, 351, 221))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser_3.setGeometry(QtCore.QRect(10, 60, 70, 30))
        self.textBrowser_3.setOpenExternalLinks(False)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.amp_420_1 = QtWidgets.QLineEdit(self.groupBox)
        self.amp_420_1.setGeometry(QtCore.QRect(90, 60, 70, 30))
        self.amp_420_1.setObjectName("amp_420_1")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser_4.setGeometry(QtCore.QRect(170, 60, 71, 31))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser_5.setGeometry(QtCore.QRect(10, 140, 70, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_5.sizePolicy().hasHeightForWidth())
        self.textBrowser_5.setSizePolicy(sizePolicy)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 100, 101, 30))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.start_frequency_420_1 = QtWidgets.QLineEdit(self.groupBox)
        self.start_frequency_420_1.setGeometry(QtCore.QRect(120, 100, 70, 30))
        self.start_frequency_420_1.setObjectName("start_frequency_420_1")
        self.end_frequency_420_1 = QtWidgets.QLineEdit(self.groupBox)
        self.end_frequency_420_1.setGeometry(QtCore.QRect(200, 100, 70, 30))
        self.end_frequency_420_1.setObjectName("end_frequency_420_1")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser.setGeometry(QtCore.QRect(280, 100, 61, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.amp_420_2 = QtWidgets.QLineEdit(self.groupBox)
        self.amp_420_2.setGeometry(QtCore.QRect(90, 140, 70, 30))
        self.amp_420_2.setObjectName("amp_420_2")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser_6.setGeometry(QtCore.QRect(10, 180, 70, 30))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.amp_420_3 = QtWidgets.QLineEdit(self.groupBox)
        self.amp_420_3.setGeometry(QtCore.QRect(90, 180, 70, 30))
        self.amp_420_3.setObjectName("amp_420_3")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser_7.setGeometry(QtCore.QRect(170, 140, 70, 30))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser_8.setGeometry(QtCore.QRect(170, 180, 70, 30))
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.checkBox_420_1 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_420_1.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.checkBox_420_1.setObjectName("checkBox_420_1")
        self.waveform_420_1 = QtWidgets.QComboBox(self.groupBox)
        self.waveform_420_1.setGeometry(QtCore.QRect(80, 10, 161, 31))
        self.waveform_420_1.setObjectName("waveform_420_1")
        self.waveform_420_1.addItem("")
        self.waveform_420_1.addItem("")
        self.waveform_420_1.addItem("")
        config.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(config)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 21))
        self.menubar.setObjectName("menubar")
        config.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(config)
        self.statusbar.setObjectName("statusbar")
        config.setStatusBar(self.statusbar)

        self.retranslateUi(config)
        QtCore.QMetaObject.connectSlotsByName(config)

    def retranslateUi(self, config):
        _translate = QtCore.QCoreApplication.translate
        config.setWindowTitle(_translate("config", "MainWindow"))
        self.done.setText(_translate("config", "Done!"))
        self.open_card.setText(_translate("config", "Open Card"))
        self.close_card.setText(_translate("config", "Close Card"))
        self.clock_frequency.setItemText(0, _translate("config", "1.25 GHz"))
        self.clock_frequency.setItemText(1, _translate("config", "1 GHz"))
        self.clock_frequency.setItemText(2, _translate("config", "750MHz"))
        self.clock_frequency.setItemText(3, _translate("config", "500 MHz"))
        self.clock_frequency.setItemText(4, _translate("config", "200 MHz"))
        self.clock_frequency.setItemText(5, _translate("config", "100 MHz"))
        self.output_mode.setItemText(0, _translate("config", "singleshot"))
        self.output_mode.setItemText(1, _translate("config", "single restart"))
        self.output_mode.setItemText(2, _translate("config", "multiplr restart"))
        self.output_mode.setItemText(3, _translate("config", "FIFO"))
        self.textBrowser_3.setHtml(_translate("config", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">amp</p></body></html>"))
        self.textBrowser_4.setHtml(_translate("config", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">%</p></body></html>"))
        self.textBrowser_5.setHtml(_translate("config", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">time</p></body></html>"))
        self.textBrowser_2.setHtml(_translate("config", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">frequency</span></p></body></html>"))
        self.textBrowser.setHtml(_translate("config", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">MHz</span></p></body></html>"))
        self.textBrowser_6.setHtml(_translate("config", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">wait</span></p></body></html>"))
        self.textBrowser_7.setHtml(_translate("config", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">us</p></body></html>"))
        self.textBrowser_8.setHtml(_translate("config", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">us</span></p></body></html>"))
        self.checkBox_420_1.setText(_translate("config", "420_1"))
        self.waveform_420_1.setItemText(0, _translate("config", "flat pulse"))
        self.waveform_420_1.setItemText(1, _translate("config", "blackman pulse"))
        self.waveform_420_1.setItemText(2, _translate("config", "ramp frequency"))
